version: '3.7'

services:
    nginx:
        build:
            args:
                VERSION: $NGINX_VERSION
            context: ../
            dockerfile: ./docker2/nginx/Dockerfile
            target: dev
        depends_on:
            - php-fpm
        ports:
            - 8000:80
    php-fpm:
        build:
            args:
                VERSION: $PHP_VERSION
            context: ../
            dockerfile: ./docker2/php-fpm/Dockerfile
            target: dev
        env_file:
            -   "php-fpm/.env"
        volumes:
            - ../:/app
            - './php-fpm/99-xdebug.template:/tmp/99-xdebug.template'
        command: sh -c 'envsubst < /tmp/99-xdebug.template > /usr/local/etc/php/conf.d/99-xdebug.ini && php-fpm'
