resources:
    limits:
        cpu: 2
        memory: 1024Mi
    requests:
        cpu: 0.25
        memory: 256Mi

ingress:
    name: k8s-test
    match: Host(`tom-test-01.fagforbundet.dev`)
    certResolver: letsencrypt
    entryPoints:
        - websecure

nginx:
    name: "k8s-test-nginx"
    image: "fagforbundet.azurecr.io/symfony-k8s-test-nginx"
    port: 80

phpfpm:
    name: "k8s-test-php-fpm"
    image: "fagforbundet.azurecr.io/symfony-k8s-test-php-fpm"
    port: 9000
