resources:
    limits:
        cpu: 2
        memory: 1024Mi
    requests:
        cpu: 0.25
        memory: 256Mi

nginx:
    name: "nginx"
    image: "fagforbundet.azurecr.io/symfony-k8s-test-nginx"
    host: k8s-test.fagforbundet.no
    port: 80

phpfpm:
    name: "php-fpm"
    image: "fagforbundet.azurecr.io/symfony-k8s-test-php-fpm"
    port: 9000

imageTag: "1.5"
