apiVersion: v1
kind: Service
metadata:
    name: nginx
    labels:
        tier: backend
spec:
    selector:
        app: nginx
        tier: backend
    ports:
        -   port: 80
            protocol: TCP
