# This is a basic workflow to help you get started with Actions

name: deploy-staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -   uses: actions/checkout@v2

            # Set the Kubernetes context
            -   name: Kubernetes set context
                uses: azure/aks-set-context@v1
                with:
                    creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
                    resource-group: 'kubernetes-cluster.staging.rg'
                    cluster-name: 'kubernetes-cluster-001-vmss-staging'
                id: login

            -   uses: azure/setup-helm@v1
                id: install

            -   uses: Azure/docker-login@v1
                with:
                    login-server: fagforbundet.azurecr.io
                    username: ${{ secrets.REGISTRY_USERNAME }}
                    password: ${{ secrets.REGISTRY_PASSWORD }}

            -   name: Build docker images
                run: |
                    docker build -f docker2/nginx/Dockerfile --build-arg VERSION=1.18 -t fagforbundet.azurecr.io/symfony-k8s-test-nginx:${{ github.sha }} --target prod .
                    docker build -f docker2/php-fpm/Dockerfile --build-arg VERSION=7.4 --build-arg SYMFONY_DECRYPTION_SECRET=${{ secrets.SYMFONY_DECRYPTION_SECRET }} -t fagforbundet.azurecr.io/symfony-k8s-test-php-fpm:${{ github.sha }} --target prod .

            -   name: Push docker image to registry.
                run: |
                    docker push fagforbundet.azurecr.io/symfony-k8s-test-nginx:${{ github.sha }}
                    docker push fagforbundet.azurecr.io/symfony-k8s-test-php-fpm:${{ github.sha }}

            -   name: Deploy to kubernetes cluster.
                run: |
                    helm upgrade symfony-k8s-test ./helm --install --set-string phpfpm.env.plain.APP_ENV=prod,imageTag=${{ github.sha }}
